-- Note: 진행중인 공모전 - 기본 (10개 조회)
SELECT CONTEST_NO, CONTEST_TITLE, TRUNC(END_DATE - CREATE_DATE) AS DUE_DATE, PRICE, THUMBNAIL
FROM CONTEST
WHERE CON_STATUS = '모집중'
AND TRUNC(END_DATE - CREATE_DATE) > 0
OFFSET 0 ROWS FETCH NEXT 10 ROWS ONLY;

-- SELECT에서 DUE_DATE가 양수가 아닐 경우 0으로 처리하는 구문
SELECT CONTEST_NO, CONTEST_TITLE, PRICE, THUMBNAIL, CASE WHEN TRUNC(END_DATE - CREATE_DATE) > 0 THEN TRUNC(END_DATE - CREATE_DATE) 
                                                         WHEN TRUNC(END_DATE - CREATE_DATE) = 0 OR TRUNC(END_DATE - CREATE_DATE) < 0 THEN 0 
                                                         END AS DUE_DATE
FROM CONTEST
WHERE CON_STATUS = '모집중'
OFFSET 0 ROWS FETCH NEXT 10 ROWS ONLY;



-- Note: 진행중인 공모전 - 신규
SELECT CONTEST_NO, CONTEST_TITLE, PRICE, THUMBNAIL, CREATE_DATE
FROM CONTEST
WHERE CON_STATUS = '모집중'
ORDER BY CREATE_DATE DESC
OFFSET 0 ROWS FETCH NEXT 11 ROWS ONLY;
	

-- Note: 진행중인 공모전 - 인기
