-- 랭킹:: 총상금 랭킹 조회
SELECT RANK() OVER (ORDER BY TOTAL_PRICE DESC) AS RANK, PROFILE_IMG, MEMBER_NICK, TOTAL_PRICE
FROM MEMBER
OFFSET 0 ROWS FETCH NEXT #{offset} ROWS ONLY;





-- 랭킹 :: 우승횟수 랭킹 조회
SELECT MEMBER_NO, VICTORY_COUNT, PROFILE_IMG, MEMBER_NICK
FROM MEMBER
JOIN (
    SELECT WINNER, COUNT(MEMBER_NO) AS VICTORY_COUNT
    FROM CONTEST
    GROUP BY WINNER
    HAVING WINNER IS NOT NULL
    ORDER BY VICTORY_COUNT DESC
) VICTORY_COUNTS
ON MEMBER_NO = VICTORY_COUNTS.WINNER
ORDER BY VICTORY_COUNT DESC
OFFSET 0 ROWS FETCH NEXT #{offset} ROWS ONLY;

-- 우승자 번호 및 우승 횟수 조회
SELECT WINNER AS 우승자번호, COUNT(MEMBER_NO) AS 우승횟수
FROM CONTEST
GROUP BY WINNER
HAVING WINNER IS NOT NULL
ORDER BY 우승횟수 DESC;

-- 우승 횟수 확인용 조회문
SELECT CONTEST_NO AS 공모전번호, MEMBER_NO AS 개최기업, WINNER AS 우승개인 FROM CONTEST;

-- 우승자 확인용 조회문
SELECT MEMBER_NO, MEMBER_NICK FROM MEMBER;





-- 랭킹 :: 좋아요 랭킹 조회
SELECT MEMBER_NO, LIKE_COUNT, PROFILE_IMG, MEMBER_NICK
FROM MEMBER
JOIN (
    SELECT P_MEMBER_NO, COUNT(P_MEMBER_NO) AS LIKE_COUNT
    FROM LIKE_USER
    GROUP BY P_MEMBER_NO
) LIKE_COUNTS
ON MEMBER_NO = LIKE_COUNTS.P_MEMBER_NO
ORDER BY LIKE_COUNTS.LIKE_COUNT DESC
OFFSET 0 ROWS FETCH NEXT 10 ROWS ONLY;

-- LIKE_USER에서 좋아요 순으로 MEMBER_NO 1열 조회
SELECT P_MEMBER_NO FROM LIKE_USER GROUP BY P_MEMBER_NO ORDER BY COUNT(P_MEMBER_NO) DESC;