-- like user dummy

-- 1번 회원 좋아요 4개
INSERT INTO LIKE_USER(LIKE_USER_NO, C_MEMBER_NO, P_MEMBER_NO)
VALUES(SEQ_LIKE_USER_NO.NEXTVAL, 2, 1);

INSERT INTO LIKE_USER(LIKE_USER_NO, C_MEMBER_NO, P_MEMBER_NO)
VALUES(SEQ_LIKE_USER_NO.NEXTVAL, 4, 1);

INSERT INTO LIKE_USER(LIKE_USER_NO, C_MEMBER_NO, P_MEMBER_NO)
VALUES(SEQ_LIKE_USER_NO.NEXTVAL, 6, 1);

INSERT INTO LIKE_USER(LIKE_USER_NO, C_MEMBER_NO, P_MEMBER_NO)
VALUES(SEQ_LIKE_USER_NO.NEXTVAL, 8, 1);

-- 3번 회원 좋아요 2개

INSERT INTO LIKE_USER(LIKE_USER_NO, C_MEMBER_NO, P_MEMBER_NO)
VALUES(SEQ_LIKE_USER_NO.NEXTVAL, 2, 3);

INSERT INTO LIKE_USER(LIKE_USER_NO, C_MEMBER_NO, P_MEMBER_NO)
VALUES(SEQ_LIKE_USER_NO.NEXTVAL, 4, 3);

-- 5번 회원 좋아요 8개

INSERT INTO LIKE_USER(LIKE_USER_NO, C_MEMBER_NO, P_MEMBER_NO)
VALUES(SEQ_LIKE_USER_NO.NEXTVAL, 2, 5);

INSERT INTO LIKE_USER(LIKE_USER_NO, C_MEMBER_NO, P_MEMBER_NO)
VALUES(SEQ_LIKE_USER_NO.NEXTVAL, 4, 5);

INSERT INTO LIKE_USER(LIKE_USER_NO, C_MEMBER_NO, P_MEMBER_NO)
VALUES(SEQ_LIKE_USER_NO.NEXTVAL, 6, 5);

INSERT INTO LIKE_USER(LIKE_USER_NO, C_MEMBER_NO, P_MEMBER_NO)
VALUES(SEQ_LIKE_USER_NO.NEXTVAL, 8, 5);

INSERT INTO LIKE_USER(LIKE_USER_NO, C_MEMBER_NO, P_MEMBER_NO)
VALUES(SEQ_LIKE_USER_NO.NEXTVAL, 9, 5);

INSERT INTO LIKE_USER(LIKE_USER_NO, C_MEMBER_NO, P_MEMBER_NO)
VALUES(SEQ_LIKE_USER_NO.NEXTVAL, 10, 5);

INSERT INTO LIKE_USER(LIKE_USER_NO, C_MEMBER_NO, P_MEMBER_NO)
VALUES(SEQ_LIKE_USER_NO.NEXTVAL, 11, 5);

INSERT INTO LIKE_USER(LIKE_USER_NO, C_MEMBER_NO, P_MEMBER_NO)
VALUES(SEQ_LIKE_USER_NO.NEXTVAL, 12, 5);

-- 7번 회원 좋아요 3개

INSERT INTO LIKE_USER(LIKE_USER_NO, C_MEMBER_NO, P_MEMBER_NO)
VALUES(SEQ_LIKE_USER_NO.NEXTVAL, 2, 7);

INSERT INTO LIKE_USER(LIKE_USER_NO, C_MEMBER_NO, P_MEMBER_NO)
VALUES(SEQ_LIKE_USER_NO.NEXTVAL, 4, 7);

INSERT INTO LIKE_USER(LIKE_USER_NO, C_MEMBER_NO, P_MEMBER_NO)
VALUES(SEQ_LIKE_USER_NO.NEXTVAL, 12, 7);