-- 테이블 삭제 구문 

--DROP TABLE "MEMBER" CASCADE CONSTRAINTS;
--DROP TABLE "SKILL" CASCADE CONSTRAINTS;
--DROP TABLE "REGION"  CASCADE CONSTRAINTS;
--DROP TABLE "EVENT"  CASCADE CONSTRAINTS;
--DROP TABLE "CONTEST"  CASCADE CONSTRAINTS;
--DROP TABLE "DEV_TYPE" CASCADE CONSTRAINTS;
--DROP TABLE "CONTEST_ATTEND"  CASCADE CONSTRAINTS;
--DROP TABLE "CHAT_ROOM" CASCADE CONSTRAINTS;
--DROP TABLE "CHAT_MESSAGE" CASCADE CONSTRAINTS;
--DROP TABLE "AD" CASCADE CONSTRAINTS;
--DROP TABLE "LIKE_USER" CASCADE CONSTRAINTS;
--DROP TABLE "LIKE_CON" CASCADE CONSTRAINTS;
--DROP TABLE "CERTIFICATION" CASCADE CONSTRAINTS;
--DROP TABLE "EXCHANGE" CASCADE CONSTRAINTS;
--DROP TABLE "BANK" CASCADE CONSTRAINTS;


-- 테이블 생성
-- 멤버 테이블
CREATE TABLE "MEMBER" (
	"MEMBER_NO"	NUMBER	CONSTRAINT "PK_MEMBER" PRIMARY KEY,
	"MEMBER_TYPE"	VARCHAR2(10)  NOT NULL,
	"MEMBER_ID"	VARCHAR2(30) CONSTRAINT "UK_MEMBER_ID" UNIQUE  NOT NULL,
	"MEMBER_PW"	VARCHAR2(30)	NOT NULL,
	"MEMBER_NICK"	VARCHAR2(20)	NOT NULL,
	"PROFILE_IMG"	VARCHAR2(300),
	"PHONE"	VARCHAR2(15),
  "REGION_NO"	NUMBER	CONSTRAINT "FK_REGION_TO_MEMBER"  REFERENCES "REGION" ("REGION_NO") ON DELETE CASCADE,
	"STACK"	VARCHAR2(10),
	"SKILL" VARCHAR2(300),
	"SLOGAN"	VARCHAR2(200),
	"INTRODUCE"	VARCHAR2(1000),
	"TOTAL_PRICE" NUMBER,
	"CURR_PRICE" NUMBER,
	"ENROLL_DATE"	DATE		DEFAULT SYSDATE,
	"SECESSION_FL"	VARCHAR2(3)	DEFAULT 'N',
	"TERMS_FL"	VARCHAR2(3)	DEFAULT 'N',
	"SNS_FL"	VARCHAR2(10)	DEFAULT 'BASIC',
	"ATTEND_COUNT" NUMBER, DEFAULT 0
	"VICTORY_COUNT" NUMBER, DEFAULT 0 
);



-- 기업 지역
CREATE TABLE "REGION" (
	"REGION_NO"	NUMBER	CONSTRAINT "PK_REGION" PRIMARY KEY	NOT NULL,
	"REGION_NAME"	VARCHAR2(50)	NOT NULL
);




-- 이벤트
CREATE TABLE "EVENT" (
	"EVENT_NO"	NUMBER	CONSTRAINT "PK_EVENT" PRIMARY KEY,
	"EVENT_TITLE"	VARCHAR2(500)	NOT	NULL,
	"EVENT_THUMBNAIL"	VARCHAR2(1000)	NOT	NULL,
	"EVENT_CONTENT"	VARCHAR2(1000)	NOT	NULL,
	"BANNER_IMG"	VARCHAR2(500)		NULL,
	"AD_IMG"	VARCHAR2(500)		NULL,
	"CREATE_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"END_DATE"	DATE		NULL,
	"STATUS_FL"	VARCHAR2(20)	DEFAULT 'N'
);



-- 공모전
CREATE TABLE "CONTEST" (
	"CONTEST_NO"	NUMBER	CONSTRAINT "PK_CONTEST" PRIMARY KEY,
	"MEMBER_NO" NUMBER CONSTRAINT "FK_MEMBER_TO_CONTEST" REFERENCES "MEMBER" ("MEMBER_NO") NOT NULL ON DELETE CASCADE,
	"CONTEST_TITLE"	VARCHAR2(100)		NOT NULL,
	"TYPE_NO"	NUMBER	 CONSTRAINT "FK_DEV_TYPE_TO_CONTEST" REFERENCES "DEV_TYPE" ("TYPE_NO")	NOT NULL ON DELETE CASCADE,
	"SUBJECT"	VARCHAR2(1000)		NOT NULL,
	"QUALIFICATION"	VARCHAR2(1000)		NOT NULL,
	"ADD_INFOMATION" VARCHAR2(1000)  NULL,
	"CREATE_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"END_DATE"	DATE		NULL,
	"SKILL"	VARCHAR2(300)	NOT NULL,
	"PRICE"	NUMBER		NOT NULL,
	"THUMBNAIL"	VARCHAR2(300)		NULL,
	"AD_NO"	NUMBER	CONSTRAINT "FK_AD_TO_CONTEST" REFERENCES "AD" ("AD_NO")	NOT NULL ON DELETE CASCADE,
	"WINNER"	VARCHAR2(100)		NULL,
	"CON_STATUS" VARCHAR2(50) DEFAULT "모집중",
	"BOOKMARK_COUNT" NUMBER  DEFAULT '0'
);



-- 개발 유형 (앱/웹/모바일/게임)
CREATE TABLE "DEV_TYPE" (
	"TYPE_NO"	NUMBER	CONSTRAINT "PK_DEV_TYPE" PRIMARY KEY,
	"TYPE_NAME"	VARCHAR2(20)		NULL
);



-- 공모전 참가
CREATE TABLE "CONTEST_ATTEND" (
	"ATTEND_NO"	NUMBER	CONSTRAINT "PK_CONTEST_ATTEND" PRIMARY KEY,
	"MEMBER_NO"	NUMBER	CONSTRAINT "FK_MEMBER_TO_CONTEST_ATTEND" REFERENCES "MEMBER" ("MEMBER_NO")	NOT NULL ON DELETE CASCADE,
	"CONTEST_NO"	NUMBER	CONSTRAINT "FK_CONTEST_TO_CONTEST_ATTEND" REFERENCES "CONTEST" ("CONTEST_NO")	NOT NULL ON DELETE CASCADE,
	"DESCRIPTION"	VARCHAR2(1000)	NOT	NULL,
	"GITHUB"	VARCHAR2(200)		NOT NULL,
	"PPT_FILE"	VARCHAR2(200)	NOT NULL,
	"SKILL" VARCHAR2(500) NOT NULL
);


-- 채팅 방
CREATE TABLE "CHAT_ROOM" (
	"CR_NO"	NUMBER		CONSTRAINT "PK_CHAT_ROOM" PRIMARY KEY,
	"MEMBER_NO"	NUMBER	CONSTRAINT "FK_MEMBER_TO_CHAT_ROOM" REFERENCES "MEMBER" ("MEMBER_NO")	NOT NULL ON DELETE CASCADE,
	"CR_PRODUCE"	TIMESTAMP		NULL
);



-- 채팅 메세지
CREATE TABLE "CHAT_MESSAGE" (
	"CM_NO"	NUMBER	CONSTRAINT "PK_CHAT_MESSAGE" PRIMARY KEY ,
	"MEMBER_NO"	NUMBER	CONSTRAINT "FK_MEMBER_TO_CHAT_MESSAGE" REFERENCES "MEMBER" ("MEMBER_NO")	NOT NULL ON DELETE CASCADE,
	"CR_NO"	NUMBER	CONSTRAINT "FK_CHAT_ROOM_TO_CHAT_MESSAGE" REFERENCES "CHAT_ROOM" ("CR_NO")	NOT NULL,
	"MESSAGE"	VARCHAR2(4000)		NOT NULL,
	"CM_TIME"	TIMESTAMP	WITH LOCAL TIME ZONE	NOT NULL,
	"READ_OR_NOT"	VARCHAR2(3)		NULL
);

-- 채팅 방 목록
CREATE TABLE CHAT_ROOM_JOIN (
MEMBER_NO NUMBER REFERENCES MEMBER,
CHAT_ROOM_NO NUMBER REFERENCES CHAT_ROOM,
PRIMARY KEY(MEMBER_NO, CHAT_ROOM_NO)
);

-- 광고
CREATE TABLE "AD" (
	"AD_NO"	NUMBER	CONSTRAINT "PK_AD" PRIMARY KEY	NOT NULL,
	"AD_TYPE"	VARCHAR2(20)		NOT NULL
);



-- 기업이 개발자 좋아요
CREATE TABLE "LIKE_USER" (
	"LIKE_USER_NO"	NUMBER	CONSTRAINT "PK_LIKE_USER" PRIMARY KEY,
	"C_MEMBER_NO"	NUMBER	CONSTRAINT "FK_MEMBER_TO_LIKE_USER_C" REFERENCES "MEMBER" ("MEMBER_NO")	NOT NULL ON DELETE CASCADE,
	"P_MEMBER_NO"	NUMBER	CONSTRAINT "FK_MEMBER_TO_LIKE_USER_P" REFERENCES "MEMBER" ("MEMBER_NO")	NOT NULL ON DELETE CASCADE
);



-- 개발자가 공모전 좋아요
CREATE TABLE "LIKE_CON" (
	"LIKE_CON_NO"	NUMBER	CONSTRAINT "PK_LIKE_CON" PRIMARY KEY,
	"MEMBER_NO"	NUMBER	CONSTRAINT "FK_MEMBER_TO_LIKE_CON" REFERENCES "MEMBER" ("MEMBER_NO")	NOT NULL ON DELETE CASCADE,
	"CONTEST_NO"	NUMBER	CONSTRAINT "FK_CONTEST_TO_LIKE_CON" REFERENCES "CONTEST" ("CONTEST_NO")	NOT NULL ON DELETE CASCADE
);



-- 인증번호
CREATE TABLE "CERTIFICATION" (
	"CLIST_NO"	NUMBER	CONSTRAINT "PK_CERTIFICATION" PRIMARY KEY,
	"MEMBER_NO"	NUMBER	CONSTRAINT "FK_MEMBER_TO_CERTIFICATION" REFERENCES "MEMBER" ("MEMBER_NO")	NOT NULL ON DELETE CASCADE,
	"ISSUE_DT"	DATE	DEFAULT SYSDATE	NULL,
	"C_NUMBER"	CHAR(6)		NOT NULL,
	"C_PHONE"	NUMBER		NULL,
	"C_EMAIL"	VARCHAR2(50)		NULL
);


-- 크레딧 인출
CREATE TABLE "EXCHANGE" (
	"MEMBER_NO"	NUMBER	CONSTRAINT "FK_MEMBER_TO_EXCHANGE" REFERENCES "MEMBER" ("MEMBER_NO")	NOT NULL ON DELETE CASCADE,
	"BANK_NO"	NUMBER	CONSTRAINT "FK_BANK_TO_EXCHANGE" REFERENCES "BANK" ("BANK_NO")	NOT NULL ON DELETE CASCADE,
	"MEMBER_NAME"	VARCHAR2(30)		NOT NULL,
	"SECURITY_NO"	VARCHAR2(15)		NOT NULL,
	"ACCOUNT_NO"	VARCHAR2(30)		NOT NULL,
	"AMOUNT"	NUMBER		NOT NULL
);


-- 은행
CREATE TABLE "BANK" (
	"BANK_NO"	NUMBER	CONSTRAINT "PK_BANK" PRIMARY KEY ,
	"BANK_NAME"	VARCHAR2(30)	NOT	NULL
);

-- 결제
CREATE TABLE "PAY" (
	"ORDER_NO"	VARCHAR2(100),
	"MEMBER_NO"	NUMBER,
	"MEMBER_NICK"	VARCHAR2(100),
	"MEMBER_TEL"	VARCHAR2(100),
	"PRODUCT_NAME"	VARCHAR2(200),
	"ORDER_DATE"	VARCHAR2(100),
	"TOTAL_PRICE"	NUMBER,
	"IMP_UID"	VARCHAR2(100)
);

-- 테이블 값 삽입 구문

-- AD_TABLE VALUE
INSERT INTO AD (AD_NO , AD_TYPE, AD_AMOUNT)
VALUES(1 , "일반형", 30);
INSERT INTO AD (AD_NO , AD_TYPE, AD_AMOUNT)
VALUES(2 , "고급형", 50)
INSERT INTO AD (AD_NO , AD_TYPE, AD_AMOUNT)
VALUES(3 , "프리미엄", 100);


-- DEV_TYPE TABLE VALUES
INSERT INTO DEV_TYPE (TYPE_NO , TYPE_NAME)
VALUES(1 ,'모바일');
INSERT INTO DEV_TYPE (TYPE_NO , TYPE_NAME)
VALUES(2 , '웹');
INSERT INTO DEV_TYPE (TYPE_NO , TYPE_NAME)
VALUES(3 , '게임');
INSERT INTO DEV_TYPE (TYPE_NO , TYPE_NAME)
VALUES(4 , '보안');


-- REGION TABLE VALUE
INSERT INTO REGION (REGION_NO, REGION_NAME)
VALUES (1, '서울');
INSERT INTO REGION (REGION_NO, REGION_NAME)
VALUES (2, '부산');
INSERT INTO REGION (REGION_NO, REGION_NAME)
VALUES (3, '대구');
INSERT INTO REGION (REGION_NO, REGION_NAME)
VALUES (4, '인천');
INSERT INTO REGION (REGION_NO, REGION_NAME)
VALUES (5, '광주');
INSERT INTO REGION (REGION_NO, REGION_NAME)
VALUES (6, '대전');
INSERT INTO REGION (REGION_NO, REGION_NAME)
VALUES (7, '울산');
INSERT INTO REGION (REGION_NO, REGION_NAME)
VALUES (8, '세종'); 
INSERT INTO REGION (REGION_NO, REGION_NAME)
VALUES (9, '경기');
INSERT INTO REGION (REGION_NO, REGION_NAME)
VALUES (10, '강원'); 
INSERT INTO REGION (REGION_NO, REGION_NAME)
VALUES (11, '충북');
INSERT INTO REGION (REGION_NO, REGION_NAME)
VALUES (12, '충남');
INSERT INTO REGION (REGION_NO, REGION_NAME)
VALUES (13, '전북'); 
INSERT INTO REGION (REGION_NO, REGION_NAME)
VALUES (14, '전남');
INSERT INTO REGION (REGION_NO, REGION_NAME)
VALUES (15, '경북');
INSERT INTO REGION (REGION_NO, REGION_NAME)
VALUES (16, '경남');
INSERT INTO REGION (REGION_NO, REGION_NAME)
VALUES (17, '제주');